### ISSUE TITLE
Keycloak crashes when plugin is included

### ISSUE THREAD

**Issue by pierre-josselin** [FIWARE/keycloak-vc-issuer#26]
When I include the JAR plugin (0.5.0) I get the following error:

```
keycloak-keycloak-1         | ERROR: Unexpected error when starting the server in (production) mode
keycloak-keycloak-1         | ERROR: Failed to start quarkus
keycloak-keycloak-1         | ERROR: javax/ws/rs/InternalServerErrorException
keycloak-keycloak-1         | ERROR: javax.ws.rs.InternalServerErrorException
keycloak-keycloak-1         | For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
keycloak-keycloak-1 exited with code 1
```

Here is my docker compose script:

```yml
version: "3"
services:
  postgre-sql:
    image: "postgres:15.4"
    hostname: "postgre-sql"
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
    restart: "always"
    volumes:
      - "./postgre-sql:/var/lib/postgresql/data"

  walt-id-ssi-kit:
    image: "waltid/ssikit:latest"
    hostname: "walt-id-ssi-kit"
    command: ["serve", "-b", "0.0.0.0"]
    restart: "always"
    volumes:
      - "./walt-id-ssi-kit:/app/data/revocation"

  keycloak:
    image: "quay.io/keycloak/keycloak:22.0.1"
    hostname: "keycloak"
    environment:
      KC_LOG_LEVEL: "ALL"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME_URL: "https://keycloak.example.com"
      KC_HOSTNAME_ADMIN_URL: "https://keycloak.example.com"
      KC_DB: "postgres"
      KC_DB_URL_HOST: "postgre-sql"
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_PROXY: "passthrough"
      KC_HTTP_ENABLED: "true"
      VCISSUER_WALTID_ADDRESS: "http://walt-id-ssi-kit"
      VCISSUER_WALTID_CORE_PORT: 7000
      VCISSUER_WALTID_SIGNATORY_PORT: 7001
      VCISSUER_ISSUER_DID: "did:web:example.com"
      VCISSUER_ISSUER_KEY_FILE: "/opt/keys/did.json"
    command: "start"
    restart: "always"
    volumes:
      - "./vc-issuer-0.5.0.jar:/opt/keycloak/providers/vc-issuer-0.5.0.jar"
      - "./did.json:/opt/keys/did.json"
    depends_on:
      - "postgre-sql"
      - "walt-id-ssi-kit"

  nginx:
    image: "nginx:1.23.4"
    hostname: "nginx"
    ports:
      - "443:443"
    restart: "always"
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - "keycloak"
```

The error disappears if I remove this line:

```yml
      - "./vc-issuer-0.5.0.jar:/opt/keycloak/providers/vc-issuer-0.5.0.jar"
```
